### ISSUE TITLE
feature_request(syntax): lodash templates syntax support

### ISSUE THREAD

**Issue by Kristinita** [alin23/Cup#2]
### 1. Summary

It would be nice, if Cup (CoffeeScript 2) will highlight [**lodash templates syntax**](https://learn.co/lessons/javascript-lodash-templates). At the time templates haven't specific scopes.

### 2. Argumentation

Personally, I use lodash templates in most of my projects CoffeeScript files, [**example**](https://github.com/Kristinita/KristinitaPelican/search?l=coffeescript). It would be nice to have user-friendly highlight as for [**Better CoffeeScript**](http://aponxi.github.io/sublime-better-coffeescript/).

### 3. Expected behavior

Better CoffeeScript — green highlight:

![Better CoffeeScript](https://i.imgur.com/82ig2p8.png)

### 4. Actual behavior

Cup — no highlight:

![Cup](https://i.imgur.com/TLrlRN0.png)

Thanks.

**Comment by alin23** [comment]
I updated the syntax to highlight code between `<%` and `%>`.

Let me know if it breaks anything.

**Comment by Kristinita** [comment]
**Status: :heavy_check_mark: Fixed for me**

Thanks!
